name: Tests

on: push

env:
    - PGPORT: 54321
    - PGDATA: $HOME/PGDATA
    - CACHE_NUMBER: 0


jobs:
    build_conda:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: [3.8, 3.9, 3.10]
                django-version: [3.2, 4.0, 4.1, 4.2]
                include:
                    - python-version: 3.11
                      django-version: 4.1
                    - python-version: 3.11
                      django-version: 4.2

        steps:
            - uses: actions/checkout@v4

            - name: Setup Mambaforge
              uses: conda-incubator/setup-miniconda@v2
              with:
                python-version: ${{matrix.python-version}}
                miniforge-variant: Mambaforge
                miniforge-version: latest
                activate-environment: my-env
                use-mamba: true
            
            - name: Install constant packages
              run: conda install -q -c rdkit rdkit rdkit-postgresql

            - name: Set cache date
              run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

            - uses: actions/cache@v3
              with:
                path: /usr/share/miniconda3/envs/my-env
                key: ubuntu-conda-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
              id: cache
            
            - name: Install variate packages
              run:
                conda install -q django~=${{matrix.django-version}} psycopg2
                python setup.py develop
            
            - name: Before tests
              run: |
                initdb
                echo "shared_preload_libraries = 'rdkit'" >> $PGDATA/postgresql.conf
                pg_ctl start -l $PGDATA/log.txt
                sleep 5 # just make sure that postgres startup has completed

            - name: Run tests
              shell: bash -l {0}
              run: python ./runtests.py