name: Tests

on: push

env:
  PGPORT: 54321
  PGDATA: $HOME/PGDATA
  CACHE_NUMBER: 0


jobs:
  container-job:
    runs-on: ubuntu-latest
    container: python:${{matrix.python-version}}-bullseye
    strategy:
      matrix:
          include:
              - python-version: "3.11"
                django-version: "4.2"
                postgresql-version: "15"
                rdkit-version: "2023_03_3"

    steps:
      - uses: actions/checkout@v4

      - name: Prepare postgresql and rdkit
        run: |
          apt-get update
          apt install -y postgresql cmake libboost-all-dev
          wget https://github.com/rdkit/rdkit/archive/Release_${{matrix.rdkit-version}}.tar.gz
          tar -xf Release_${{matrix.rdkit-version}}.tar.gz
          cd rdkit-Release_${{matrix.rdkit-version}}
          mkdir build
          cd build
          cmake .. -D RDK_BUILD_PGSQL=ON \
          -D PostgreSQL_CONFIG_DIR=/usr/lib/postgresql/13/bin \
          -D PostgreSQL_INCLUDE_DIR="/usr/include/postgresql" \
          -D PostgreSQL_TYPE_INCLUDE_DIR="/usr/include/postgresql/13/server" \
          -D PostgreSQL_LIBRARY="/usr/lib/x86_64-linux-gnu/libpq.so"
          make
          make install
          systemctl start postgresql

      - name: Install constant packages
        run: pip install rdkit psycopg2-binary
      
      - name: Install variate packages
        run: |
          pip install django~=${{matrix.django-version}}
          python setup.py develop

      - name: Run tests
        shell: bash -l {0}
        run: python ./runtests.py