name: Tests

on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: python:${{matrix.python-version}}-bullseye
    strategy:
      matrix:
        psycopg-package: ["psycopg2-binary", "psycopg[binary]"]
          include:
              - python-version: "3.11"
                django-version: "4.2"
                rdkit-cartridge-version: "2023_03_2"
                rdkit-python-version: "2023.3.2"

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: informaticsmatters/rdkit-cartridge-debian:Release_${{matrix.rdkit-cartridge-version}}
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Install constant packages
        run: pip install rdkit==${{matrix.rdkit-python-version}} ${{matrix.psycopg-package}}
      
      - name: Install variate packages
        run: |
          pip install django~=${{matrix.django-version}}
          python setup.py develop

      - name: Run tests
        shell: bash -l {0}
        run: python ./runtests.py
        env:
          DJANGO_DB: test
          DJANGO_USER: postgres
          DJANGO_PASSWORD: postgres
          DATABASE_HOST: postgres
          DATABASE_PORT: 5432